apiVersion: v1
kind: Pod
metadata:
  name: testistic-zookeeper
  labels:
    app: testistic-zookeeper
    tier: backend
spec:
  containers:
  - name: testistic-zookeeper
    image: wurstmeister/zookeeper
    ports:
    - containerPort: 2181
