apiVersion: v1
kind: Pod
metadata:
  name: testistic-kafka
  labels:
    app: testistic-kafka
    tier: backend
spec:
  containers:
  - name: testistic-kafka
    image: wurstmeister/kafka
    ports:
    - containerPort: 9092
    env:
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "testistic-zookeeper:2181"
    - name: KAFKA_ADVERTISED_HOST_NAME
      value: "testistic-kafka"
    volumeMounts:
      - mountPath: /kafka
        name: testistic-mounted-volume
  volumes:
    - name: testistic-mounted-volume
      persistentVolumeClaim:
        claimName: testistic-volume-claim