kind: Service
apiVersion: v1
metadata:
  name: testistic-api-service
spec:
  selector:
    app: testistic-api
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: LoadBalancer
status:
  loadBalancer: {}
