apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  chartname: "{{ .Chart.Name }}"
  namespace: {{ .Release.Namespace }}
  environmentPurpose: {{ .Values.purpose | lower | quote }}
  audience: {{ .Values.audience | lower | quote }}
