kind: Service
apiVersion: v1
metadata:
  name: testistic-{{ .Values.purpose | lower }}-{{ .Values.audience | lower }}-zookeeper
spec:
  selector:
    app: testistic-{{ .Values.purpose | lower }}-{{ .Values.audience | lower }}-zookeeper
  ports:
  - protocol: TCP
    port: 2181
    targetPort: 2181