kind: Service
apiVersion: v1
metadata:
  name: testistic-{{ .Values.purpose | lower }}-{{ .Values.audience | lower }}-api-service
spec:
  selector:
    app: testistic-{{ .Values.purpose | lower }}-{{ .Values.audience | lower }}-api
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: LoadBalancer
status:
  loadBalancer: {}
