apiVersion: v1
kind: Pod
metadata:
  name: testistic-{{ .Values.purpose | lower }}-{{ .Values.audience | lower }}-kafka
  labels:
    app: testistic-{{ .Values.purpose | lower }}-{{ .Values.audience | lower }}-kafka
    tier: backend
spec:
  containers:
  - name: testistic-kafka
    image: wurstmeister/kafka
    ports:
    - containerPort: 9092
    env:
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "testistic-{{ .Values.purpose | lower }}-{{ .Values.audience | lower }}-zookeeper:2181"
    - name: KAFKA_ADVERTISED_HOST_NAME
      value: "testistic-{{ .Values.purpose | lower }}-{{ .Values.audience | lower }}-kafka"
    volumeMounts:
      - mountPath: /kafka
        name: testistic-mounted-volume
  volumes:
    - name: testistic-mounted-volume
      persistentVolumeClaim:
        claimName: testistic-{{ .Values.purpose | lower }}-{{ .Values.audience | lower }}-volume-claim