apiVersion: v1
kind: Pod
metadata:
  name: testistic-{{ .Values.purpose | lower }}-{{ .Values.audience | lower }}-stream
  labels:
    app: testistic-{{ .Values.purpose | lower }}-{{ .Values.audience | lower }}-stream
    tier: backend
spec:
  containers:
  - name: testistic-stream
    image: gcr.io/testistic-216703/testistic-stream:latest
    env:
    - name: KAFKASERVICE
      value: "testistic-{{ .Values.purpose | lower }}-{{ .Values.audience | lower }}-kafka:9092"
    - name: DEBUG
      value: "kafka-node:*,kafka-client,testistic-api,testistic-repository"


