apiVersion: v1
kind: Pod
metadata:
  name: testistic-{{ .Values.purpose | lower }}-{{ .Values.audience | lower }}-zookeeper
  labels:
    app: testistic-{{ .Values.purpose | lower }}-{{ .Values.audience | lower }}-zookeeper
    tier: backend
spec:
  containers:
  - name: testistic-zookeeper
    image: wurstmeister/zookeeper
    ports:
    - containerPort: 2181
    volumeMounts:
      - mountPath: /opt/zookeeper-3.4.9/data
        name: testistic-mounted-volume
  volumes:
    - name: testistic-mounted-volume
      persistentVolumeClaim:
        claimName: testistic-volume-claim
