apiVersion: v1
kind: Pod
metadata:
  name: testistic-{{ .Values.purpose | lower }}-{{ .Values.audience | lower }}-ui
  labels:
    app: testistic-{{ .Values.purpose | lower }}-{{ .Values.audience | lower }}-ui
spec:
  containers:
  - name: testistic-ui
    image: gcr.io/testistic-216703/testistic-ui:v0.1.0
    ports:
    - containerPort: 8080
    env:
    - name: TESTISTIC_API_HOST
      value: "testistic-api"
